name: expensinfo
description: Premium Expense Tracker 2026
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_sms_inbox: ^1.0.2
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

telephony: ^0.2.0
permission_handler: ^11.3.0
